module.exports = {
  reactStrictMode: true,
  env: {
    REACT_APP_APIKEY: process.env.REACT_APP_APIKEY,
    REACT_APP_AUTHORITY: process.env.REACT_APP_AUTHORITY,
    REACT_APP_PROJECT_ID: process.env.REACT_APP_PROJECT_ID,
    REACT_APP_STORAGE_BUCKET: process.env.REACT_APP_STORAGE_BUCKET,
    REACT_APP_MESSAGING_SENDER_ID: process.env.REACT_APP_MESSAGING_SENDER_ID,
    REACT_APP_APP_ID: process.env.REACT_APP_APP_ID,
    REACT_APP_MEASUREMENT_ID: process.env.REACT_APP_MEASUREMENT_ID,
  },
};
